[custom]
;设置规则标志位
ruleset=CN,[]GEOSITE,CN
ruleset=CN,[]GEOSITE,china-list
ruleset=CN,[]GEOSITE,geolocation-cn
ruleset=CN,[]GEOIP,CN,no-resolve
ruleset=漏网之鱼,[]FINAL
;设置规则标志位

;设置分组标志位
custom_proxy_group=测试`select`[]REJECT`[]DIRECT`.*
custom_proxy_group=漏网之鱼`select`[]REJECT`[]DIRECT`[]香港专线`[]香港大流量`[]新加坡专线`[]新加坡大流量`[]日本专线`[]日本大流量`[]美国专线`[]美国大流量`[]欧洲专线`[]欧洲大流量`.*
custom_proxy_group=手动代理`select`[]REJECT`[]DIRECT`[]香港专线`[]香港大流量`[]新加坡专线`[]新加坡大流量`[]日本专线`[]日本大流量`[]美国专线`[]美国大流量`[]欧洲专线`[]欧洲大流量`.*
custom_proxy_group=SSH`select`[]REJECT`[]DIRECT`.*
custom_proxy_group=落地中转1`select`[]REJECT`^(?!.*(落地|落)).*
custom_proxy_group=落地中转2`select`[]REJECT`^(?!.*(落地|落)).*
custom_proxy_group=落地中转3`select`[]REJECT`^(?!.*(落地|落)).*
custom_proxy_group=落地中转4`select`[]REJECT`^(?!.*(落地|落)).*
custom_proxy_group=落地中转5`select`[]REJECT`^(?!.*(落地|落)).*
custom_proxy_group=落地中转6`select`[]REJECT`^(?!.*(落地|落)).*
custom_proxy_group=落地中转7`select`[]REJECT`^(?!.*(落地|落)).*
custom_proxy_group=落地中转8`select`[]REJECT`^(?!.*(落地|落)).*
custom_proxy_group=落地中转9`select`[]REJECT`^(?!.*(落地|落)).*
custom_proxy_group=落地中转10`select`[]REJECT`^(?!.*(落地|落)).*
custom_proxy_group=香港专线`select`(香港|HK)
custom_proxy_group=香港大流量`select`(香港|HK)
custom_proxy_group=新加坡专线`select`(新加坡|SG)
custom_proxy_group=新加坡大流量`select`(新加坡|SG)
custom_proxy_group=日本专线`select`(日本|JP)
custom_proxy_group=日本大流量`select`(日本|JP)
custom_proxy_group=美国专线`select`(美国|US)
custom_proxy_group=美国大流量`select`(美国|US)
custom_proxy_group=欧洲专线`select`.*
custom_proxy_group=欧洲大流量`select`.*
custom_proxy_group=Apple`select`[]REJECT`[]DIRECT`[]香港专线`[]香港大流量`[]新加坡专线`[]新加坡大流量`[]日本专线`[]日本大流量`[]美国专线`[]美国大流量`[]欧洲专线`[]欧洲大流量`.*
custom_proxy_group=Apple Music`select`[]REJECT`[]DIRECT`[]香港专线`[]香港大流量`[]新加坡专线`[]新加坡大流量`[]日本专线`[]日本大流量`[]美国专线`[]美国大流量`[]欧洲专线`[]欧洲大流量`.*
custom_proxy_group=Bank(Europe)`select`[]REJECT`[]DIRECT`[]香港专线`[]香港大流量`[]新加坡专线`[]新加坡大流量`[]日本专线`[]日本大流量`[]美国专线`[]美国大流量`[]欧洲专线`[]欧洲大流量`.*
custom_proxy_group=Bank(Hong Kong)`select`[]REJECT`[]DIRECT`[]香港专线`[]香港大流量`[]新加坡专线`[]新加坡大流量`[]日本专线`[]日本大流量`[]美国专线`[]美国大流量`[]欧洲专线`[]欧洲大流量`.*
custom_proxy_group=Bank(Malaysia)`select`[]REJECT`[]DIRECT`[]香港专线`[]香港大流量`[]新加坡专线`[]新加坡大流量`[]日本专线`[]日本大流量`[]美国专线`[]美国大流量`[]欧洲专线`[]欧洲大流量`.*
custom_proxy_group=Crypto`select`[]REJECT`[]DIRECT`[]香港专线`[]香港大流量`[]新加坡专线`[]新加坡大流量`[]日本专线`[]日本大流量`[]美国专线`[]美国大流量`[]欧洲专线`[]欧洲大流量`.*
custom_proxy_group=Crypto(Binance)`select`[]REJECT`[]DIRECT`[]香港专线`[]香港大流量`[]新加坡专线`[]新加坡大流量`[]日本专线`[]日本大流量`[]美国专线`[]美国大流量`[]欧洲专线`[]欧洲大流量`.*
custom_proxy_group=Crypto(Bybit)`select`[]REJECT`[]DIRECT`[]香港专线`[]香港大流量`[]新加坡专线`[]新加坡大流量`[]日本专线`[]日本大流量`[]美国专线`[]美国大流量`[]欧洲专线`[]欧洲大流量`.*
custom_proxy_group=Download`select`[]REJECT`[]DIRECT`[]香港专线`[]香港大流量`[]新加坡专线`[]新加坡大流量`[]日本专线`[]日本大流量`[]美国专线`[]美国大流量`[]欧洲专线`[]欧洲大流量`.*
custom_proxy_group=Download(Game)`select`[]REJECT`[]DIRECT`[]香港专线`[]香港大流量`[]新加坡专线`[]新加坡大流量`[]日本专线`[]日本大流量`[]美国专线`[]美国大流量`[]欧洲专线`[]欧洲大流量`.*
custom_proxy_group=Download(GameCN)`select`[]REJECT`[]DIRECT`[]香港专线`[]香港大流量`[]新加坡专线`[]新加坡大流量`[]日本专线`[]日本大流量`[]美国专线`[]美国大流量`[]欧洲专线`[]欧洲大流量`.*
custom_proxy_group=Email`select`[]REJECT`[]DIRECT`[]香港专线`[]香港大流量`[]新加坡专线`[]新加坡大流量`[]日本专线`[]日本大流量`[]美国专线`[]美国大流量`[]欧洲专线`[]欧洲大流量`.*
custom_proxy_group=Facebook`select`[]REJECT`[]DIRECT`[]香港专线`[]香港大流量`[]新加坡专线`[]新加坡大流量`[]日本专线`[]日本大流量`[]美国专线`[]美国大流量`[]欧洲专线`[]欧洲大流量`.*
custom_proxy_group=Game`select`[]REJECT`[]DIRECT`[]香港专线`[]香港大流量`[]新加坡专线`[]新加坡大流量`[]日本专线`[]日本大流量`[]美国专线`[]美国大流量`[]欧洲专线`[]欧洲大流量`.*
custom_proxy_group=GitHub`select`[]REJECT`[]DIRECT`[]香港专线`[]香港大流量`[]新加坡专线`[]新加坡大流量`[]日本专线`[]日本大流量`[]美国专线`[]美国大流量`[]欧洲专线`[]欧洲大流量`.*
custom_proxy_group=Google`select`[]REJECT`[]DIRECT`[]香港专线`[]香港大流量`[]新加坡专线`[]新加坡大流量`[]日本专线`[]日本大流量`[]美国专线`[]美国大流量`[]欧洲专线`[]欧洲大流量`.*
custom_proxy_group=Microsoft`select`[]REJECT`[]DIRECT`[]香港专线`[]香港大流量`[]新加坡专线`[]新加坡大流量`[]日本专线`[]日本大流量`[]美国专线`[]美国大流量`[]欧洲专线`[]欧洲大流量`.*
custom_proxy_group=OneDrive`select`[]REJECT`[]DIRECT`[]香港专线`[]香港大流量`[]新加坡专线`[]新加坡大流量`[]日本专线`[]日本大流量`[]美国专线`[]美国大流量`[]欧洲专线`[]欧洲大流量`.*
custom_proxy_group=PayPal`select`[]REJECT`[]DIRECT`[]香港专线`[]香港大流量`[]新加坡专线`[]新加坡大流量`[]日本专线`[]日本大流量`[]美国专线`[]美国大流量`[]欧洲专线`[]欧洲大流量`.*
custom_proxy_group=Riot`select`[]REJECT`[]DIRECT`[]香港专线`[]香港大流量`[]新加坡专线`[]新加坡大流量`[]日本专线`[]日本大流量`[]美国专线`[]美国大流量`[]欧洲专线`[]欧洲大流量`.*
custom_proxy_group=Spotify`select`[]REJECT`[]DIRECT`[]香港专线`[]香港大流量`[]新加坡专线`[]新加坡大流量`[]日本专线`[]日本大流量`[]美国专线`[]美国大流量`[]欧洲专线`[]欧洲大流量`.*
custom_proxy_group=Steam`select`[]REJECT`[]DIRECT`[]香港专线`[]香港大流量`[]新加坡专线`[]新加坡大流量`[]日本专线`[]日本大流量`[]美国专线`[]美国大流量`[]欧洲专线`[]欧洲大流量`.*
custom_proxy_group=Steam(CN)`select`[]REJECT`[]DIRECT`[]香港专线`[]香港大流量`[]新加坡专线`[]新加坡大流量`[]日本专线`[]日本大流量`[]美国专线`[]美国大流量`[]欧洲专线`[]欧洲大流量`.*
custom_proxy_group=Telegram`select`[]REJECT`[]DIRECT`[]香港专线`[]香港大流量`[]新加坡专线`[]新加坡大流量`[]日本专线`[]日本大流量`[]美国专线`[]美国大流量`[]欧洲专线`[]欧洲大流量`.*
custom_proxy_group=TikTok`select`[]REJECT`[]DIRECT`[]香港专线`[]香港大流量`[]新加坡专线`[]新加坡大流量`[]日本专线`[]日本大流量`[]美国专线`[]美国大流量`[]欧洲专线`[]欧洲大流量`.*
custom_proxy_group=Whatsapp`select`[]REJECT`[]DIRECT`[]香港专线`[]香港大流量`[]新加坡专线`[]新加坡大流量`[]日本专线`[]日本大流量`[]美国专线`[]美国大流量`[]欧洲专线`[]欧洲大流量`.*
custom_proxy_group=X`select`[]REJECT`[]DIRECT`[]香港专线`[]香港大流量`[]新加坡专线`[]新加坡大流量`[]日本专线`[]日本大流量`[]美国专线`[]美国大流量`[]欧洲专线`[]欧洲大流量`.*
custom_proxy_group=XiaoMi`select`[]REJECT`[]DIRECT`[]香港专线`[]香港大流量`[]新加坡专线`[]新加坡大流量`[]日本专线`[]日本大流量`[]美国专线`[]美国大流量`[]欧洲专线`[]欧洲大流量`.*
custom_proxy_group=YouTube`select`[]REJECT`[]DIRECT`[]香港专线`[]香港大流量`[]新加坡专线`[]新加坡大流量`[]日本专线`[]日本大流量`[]美国专线`[]美国大流量`[]欧洲专线`[]欧洲大流量`.*
custom_proxy_group=VoWiFi`select`[]REJECT`[]DIRECT`.*
custom_proxy_group=VoWiFi爱沙尼亚`select`[]REJECT`[]DIRECT`.*
custom_proxy_group=VoWiFi奥地利`select`[]REJECT`[]DIRECT`.*
custom_proxy_group=VoWiFi澳大利亚`select`[]REJECT`[]DIRECT`.*
custom_proxy_group=VoWiFi澳门`select`[]REJECT`[]DIRECT`.*
custom_proxy_group=VoWiFi保加利亚`select`[]REJECT`[]DIRECT`.*
custom_proxy_group=VoWiFi波兰`select`[]REJECT`[]DIRECT`.*
custom_proxy_group=VoWiFi德国`select`[]REJECT`[]DIRECT`.*
custom_proxy_group=VoWiFi菲律宾`select`[]REJECT`[]DIRECT`.*
custom_proxy_group=VoWiFi格鲁吉亚`select`[]REJECT`[]DIRECT`.*
custom_proxy_group=VoWiFi哈萨克斯坦`select`[]REJECT`[]DIRECT`.*
custom_proxy_group=VoWiFi荷兰`select`[]REJECT`[]DIRECT`.*
custom_proxy_group=VoWiFi克罗地亚`select`[]REJECT`[]DIRECT`.*
custom_proxy_group=VoWiFi肯尼亚`select`[]REJECT`[]DIRECT`.*
custom_proxy_group=VoWiFi马耳他`select`[]REJECT`[]DIRECT`.*
custom_proxy_group=VoWiFi马来西亚`select`[]REJECT`[]DIRECT`.*
custom_proxy_group=VoWiFi南非`select`[]REJECT`[]DIRECT`.*
custom_proxy_group=VoWiFi瑞士`select`[]REJECT`[]DIRECT`.*
custom_proxy_group=VoWiFi萨尔瓦多`select`[]REJECT`[]DIRECT`.*
custom_proxy_group=VoWiFi塞尔维亚`select`[]REJECT`[]DIRECT`.*
custom_proxy_group=VoWiFi斯里兰卡`select`[]REJECT`[]DIRECT`.*
custom_proxy_group=VoWiFi乌克兰`select`[]REJECT`[]DIRECT`.*
custom_proxy_group=VoWiFi香港`select`[]REJECT`[]DIRECT`.*
custom_proxy_group=VoWiFi新西兰`select`[]REJECT`[]DIRECT`.*
custom_proxy_group=VoWiFi印度尼西亚`select`[]REJECT`[]DIRECT`.*
custom_proxy_group=VoWiFi英国`select`[]REJECT`[]DIRECT`.*
custom_proxy_group=CN`select`[]REJECT`[]DIRECT`.*
;设置分组标志位

enable_rule_generator=true
overwrite_original_rules=true
